### ISSUE TITLE
Long Card Pressed Listener

### ISSUE THREAD

**Issue by vrjgamer** [wenchaojiang/AndroidSwipeableCardStack#12]
is it possible to set a long pressed or double tap listener for top card?

or is it possible for u to include the method of the class "SimpleGestureListener " onLongPress() and onDoubleTap() here -

```
    class MyGestureListener extends GestureDetector.SimpleOnGestureListener {
    public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX,
                            float distanceY) {
        if(mListener == null) return true;
        if( mStarted == false){
            mListener.onDragStart(e1,e2,distanceX,distanceY);
            mStarted = true;
        }
        else{
            mListener.onDragContinue(e1,e2,distanceX,distanceY);
        }
        mOriginalEvent = e1;
        return true;
    }

    @Override
    public boolean onSingleTapUp(MotionEvent e) {

        return mListener.onTapUp();
    }
}
```

it will really come in handy for all.
And I need that too for my App.

But Good Work Man!! :+1:

**Comment by wenchaojiang** [comment]
You can not do it currently. Will consider it as an extra feature

**Comment by wenchaojiang** [comment]
I do not see any problem of adding extra gesture detection in this way.
I suggest to use onSingleTapConfirmed() instead of onSingleTapUp(), because you want to distinguish single tap and double tap. 

You can modify DragListener interface to forward the events it to cardstack class.

Let me  know how you are getting on and u are welcome for pull request
